/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoeditortexto;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author SENA
 */
public class FrmEditorTexto extends javax.swing.JFrame {

    /**
     * Creates new form FrmEditorTexto
     */
    public FrmEditorTexto() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuAuxiliar = new javax.swing.JPopupMenu();
        menuNegrillaAuxiliar = new javax.swing.JMenuItem();
        menuAuxiliarRojo = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTexto = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        cbEstilos = new javax.swing.JComboBox<>();
        btnNegrilla = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuArial = new javax.swing.JMenuItem();
        menuTimesNewRoman = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuNormal = new javax.swing.JMenuItem();
        menuNegrilla = new javax.swing.JMenuItem();
        menuCursiva = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu8 = new javax.swing.JMenuItem();
        menu14 = new javax.swing.JMenuItem();
        menu20 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuRojo = new javax.swing.JMenuItem();
        menuAzul = new javax.swing.JMenuItem();
        menuAmarillo = new javax.swing.JMenuItem();
        menuNegro = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuMayuscula = new javax.swing.JMenuItem();
        menuMinuscula = new javax.swing.JMenuItem();

        menuNegrillaAuxiliar.setText("Negrilla");
        menuNegrillaAuxiliar.setComponentPopupMenu(menuAuxiliar);
        menuNegrillaAuxiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNegrillaAuxiliarActionPerformed(evt);
            }
        });
        menuAuxiliar.add(menuNegrillaAuxiliar);

        menuAuxiliarRojo.setText("Rojo");
        menuAuxiliarRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAuxiliarRojoActionPerformed(evt);
            }
        });
        menuAuxiliar.add(menuAuxiliarRojo);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTexto.setColumns(20);
        txtTexto.setRows(5);
        txtTexto.setComponentPopupMenu(menuAuxiliar);
        txtTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTextoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtTexto);

        jToolBar1.setRollover(true);

        cbEstilos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arial", "Times New Roman", "Calibri", "Comc Sans" }));
        cbEstilos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstilosActionPerformed(evt);
            }
        });
        jToolBar1.add(cbEstilos);

        btnNegrilla.setText("jButton1");
        btnNegrilla.setFocusable(false);
        btnNegrilla.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNegrilla.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNegrilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegrillaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNegrilla);

        jLabel1.setText("cantidad palabras:");

        lblCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCantidadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        jMenu1.setText("Fuente");

        menuArial.setText("Arial");
        menuArial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArialActionPerformed(evt);
            }
        });
        jMenu1.add(menuArial);

        menuTimesNewRoman.setText("Times New Roman");
        menuTimesNewRoman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTimesNewRomanActionPerformed(evt);
            }
        });
        jMenu1.add(menuTimesNewRoman);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Estilo");

        menuNormal.setText("Normal");
        menuNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNormalActionPerformed(evt);
            }
        });
        jMenu5.add(menuNormal);

        menuNegrilla.setText("Negrilla");
        menuNegrilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNegrillaActionPerformed(evt);
            }
        });
        jMenu5.add(menuNegrilla);

        menuCursiva.setText("Cursiva");
        menuCursiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCursivaActionPerformed(evt);
            }
        });
        jMenu5.add(menuCursiva);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Tamaño");

        menu8.setText("8");
        menu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu8ActionPerformed(evt);
            }
        });
        jMenu2.add(menu8);

        menu14.setText("14");
        menu14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu14ActionPerformed(evt);
            }
        });
        jMenu2.add(menu14);

        menu20.setText("20");
        menu20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu20ActionPerformed(evt);
            }
        });
        jMenu2.add(menu20);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Color");

        menuRojo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuRojo.setText("Rojo");
        menuRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRojoActionPerformed(evt);
            }
        });
        jMenu3.add(menuRojo);

        menuAzul.setText("Azul");
        menuAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAzulActionPerformed(evt);
            }
        });
        jMenu3.add(menuAzul);

        menuAmarillo.setText("Amarillo");
        menuAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAmarilloActionPerformed(evt);
            }
        });
        jMenu3.add(menuAmarillo);

        menuNegro.setText("Negro");
        menuNegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNegroActionPerformed(evt);
            }
        });
        jMenu3.add(menuNegro);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("May/Min");

        menuMayuscula.setText("Mayuscula");
        menuMayuscula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMayusculaActionPerformed(evt);
            }
        });
        jMenu4.add(menuMayuscula);

        menuMinuscula.setText("Minuscula");
        menuMinuscula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMinusculaActionPerformed(evt);
            }
        });
        jMenu4.add(menuMinuscula);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuTimesNewRomanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTimesNewRomanActionPerformed
        Font fuente = new Font("Times New Roman", txtTexto.getFont().getStyle(), txtTexto.getFont().getSize());
        txtTexto.getFont().getSize();
        txtTexto.setFont(fuente);
    }//GEN-LAST:event_menuTimesNewRomanActionPerformed

    private void menuArialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArialActionPerformed
        Font fuente = new Font("Arial", txtTexto.getFont().getStyle(), txtTexto.getFont().getSize());
        txtTexto.getFont().getSize();
        txtTexto.setFont(fuente);
    }//GEN-LAST:event_menuArialActionPerformed

    private void menuNegrillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNegrillaActionPerformed
        Font fuente = new Font(txtTexto.getFont().getFontName(), Font.BOLD, txtTexto.getFont().getSize());
        txtTexto.getFont().getSize();
        txtTexto.setFont(fuente);
    }//GEN-LAST:event_menuNegrillaActionPerformed

    private void menu20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu20ActionPerformed
        Font fuente = new Font(txtTexto.getFont().getFontName(), txtTexto.getFont().getStyle(), 20);
        txtTexto.getFont().getSize();
        txtTexto.setFont(fuente);
    }//GEN-LAST:event_menu20ActionPerformed

    private void menuCursivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCursivaActionPerformed
        Font fuente = new Font(txtTexto.getFont().getFontName(), Font.ITALIC, txtTexto.getFont().getSize());
        txtTexto.getFont().getSize();
        txtTexto.setFont(fuente);
    }//GEN-LAST:event_menuCursivaActionPerformed

    private void menuNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNormalActionPerformed
        Font fuente = new Font(txtTexto.getFont().getFontName(), Font.PLAIN, txtTexto.getFont().getSize());
        txtTexto.getFont().getSize();
        txtTexto.setFont(fuente);
    }//GEN-LAST:event_menuNormalActionPerformed

    private void menu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu8ActionPerformed
        Font fuente = new Font(txtTexto.getFont().getFontName(), txtTexto.getFont().getStyle(), 8);
        txtTexto.getFont().getSize();
        txtTexto.setFont(fuente);
    }//GEN-LAST:event_menu8ActionPerformed

    private void menu14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu14ActionPerformed
        Font fuente = new Font(txtTexto.getFont().getFontName(), txtTexto.getFont().getStyle(), 14);
        txtTexto.getFont().getSize();
        txtTexto.setFont(fuente);
    }//GEN-LAST:event_menu14ActionPerformed

    private void menuRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRojoActionPerformed
        txtTexto.setForeground(Color.RED);
    }//GEN-LAST:event_menuRojoActionPerformed

    private void menuAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAzulActionPerformed
        txtTexto.setForeground(Color.BLUE);
    }//GEN-LAST:event_menuAzulActionPerformed

    private void menuAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAmarilloActionPerformed
        txtTexto.setForeground(Color.YELLOW);
    }//GEN-LAST:event_menuAmarilloActionPerformed

    private void menuNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNegroActionPerformed
        txtTexto.setForeground(Color.BLACK);
    }//GEN-LAST:event_menuNegroActionPerformed

    private void menuMayusculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMayusculaActionPerformed
        txtTexto.setText(txtTexto.getText().toUpperCase());
    }//GEN-LAST:event_menuMayusculaActionPerformed

    private void menuMinusculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMinusculaActionPerformed
        txtTexto.setText(txtTexto.getText().toLowerCase());
    }//GEN-LAST:event_menuMinusculaActionPerformed

    private void menuAuxiliarRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAuxiliarRojoActionPerformed
        txtTexto.setForeground(Color.RED);
    }//GEN-LAST:event_menuAuxiliarRojoActionPerformed

    private void menuNegrillaAuxiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNegrillaAuxiliarActionPerformed
        Font fuente = new Font(txtTexto.getFont().getFontName(), Font.BOLD, txtTexto.getFont().getSize());
        txtTexto.getFont().getSize();
        txtTexto.setFont(fuente);
    }//GEN-LAST:event_menuNegrillaAuxiliarActionPerformed

    private void cbEstilosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstilosActionPerformed
        String letra = cbEstilos.getSelectedItem().toString();
        Font fuente = new Font(letra, txtTexto.getFont().getStyle(), txtTexto.getFont().getSize());
        txtTexto.getFont().getSize();
        txtTexto.setFont(fuente);
    }//GEN-LAST:event_cbEstilosActionPerformed

    private void btnNegrillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegrillaActionPerformed
        Font fuente = new Font(txtTexto.getFont().getFontName(), Font.BOLD, txtTexto.getFont().getSize());
        txtTexto.getFont().getSize();
        txtTexto.setFont(fuente);
    }//GEN-LAST:event_btnNegrillaActionPerformed

    private void lblCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCantidadMouseClicked

    }//GEN-LAST:event_lblCantidadMouseClicked

    private void txtTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTextoKeyPressed
        String[] texto = txtTexto.getText().split(" ");
        int cantidadPalabras = texto.length;
        lblCantidad.setText(String.valueOf(cantidadPalabras));
    }//GEN-LAST:event_txtTextoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditorTexto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNegrilla;
    private javax.swing.JComboBox<String> cbEstilos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JMenuItem menu14;
    private javax.swing.JMenuItem menu20;
    private javax.swing.JMenuItem menu8;
    private javax.swing.JMenuItem menuAmarillo;
    private javax.swing.JMenuItem menuArial;
    private javax.swing.JPopupMenu menuAuxiliar;
    private javax.swing.JMenuItem menuAuxiliarRojo;
    private javax.swing.JMenuItem menuAzul;
    private javax.swing.JMenuItem menuCursiva;
    private javax.swing.JMenuItem menuMayuscula;
    private javax.swing.JMenuItem menuMinuscula;
    private javax.swing.JMenuItem menuNegrilla;
    private javax.swing.JMenuItem menuNegrillaAuxiliar;
    private javax.swing.JMenuItem menuNegro;
    private javax.swing.JMenuItem menuNormal;
    private javax.swing.JMenuItem menuRojo;
    private javax.swing.JMenuItem menuTimesNewRoman;
    private javax.swing.JTextArea txtTexto;
    // End of variables declaration//GEN-END:variables
}
